
#include "external/fonts.h"

#include "base/base_incl.h"
#include "os/os_incl.h"
#include "graphics/graphics_incl.h"
#include "audio/audio_incl.h"
#include "renderer_2d/renderer_2d_incl.h"
#include "renderer_line/renderer_line_incl.h"
#include "font/font_incl.h"
#include "draw/draw_incl.h"
#include "ui/ui_incl.h"
#include "ui/ui_widgets.h"

#include "base/base_incl.c"
#include "os/os_incl.c"
#include "graphics/graphics_incl.c"
#include "audio/audio_incl.c"
#include "renderer_2d/renderer_2d_incl.c"
#include "renderer_line/renderer_line_incl.c"
#include "font/font_incl.c"
#include "draw/draw_incl.c"
#include "ui/ui_incl.c"
#include "ui/ui_widgets.c"

#include "arrows_incl.h"
#include "arrows_incl.c"
