
G_KeyDef(None, "No Key", False)

G_KeyDef(GraveAccent, "Grave", True)
G_KeyDef(0, "0", True)
G_KeyDef(1, "1", True)
G_KeyDef(2, "2", True)
G_KeyDef(3, "3", True)
G_KeyDef(4, "4", True)
G_KeyDef(5, "5", True)
G_KeyDef(6, "6", True)
G_KeyDef(7, "7", True)
G_KeyDef(8, "8", True)
G_KeyDef(9, "9", True)
G_KeyDef(Minus, "Minus", True)
G_KeyDef(Equal, "Equal", True)
G_KeyDef(A, "A", True)
G_KeyDef(B, "B", True)
G_KeyDef(C, "C", True)
G_KeyDef(D, "D", True)
G_KeyDef(E, "E", True)
G_KeyDef(F, "F", True)
G_KeyDef(G, "G", True)
G_KeyDef(H, "H", True)
G_KeyDef(I, "I", True)
G_KeyDef(J, "J", True)
G_KeyDef(K, "K", True)
G_KeyDef(L, "L", True)
G_KeyDef(M, "M", True)
G_KeyDef(N, "N", True)
G_KeyDef(O, "O", True)
G_KeyDef(P, "P", True)
G_KeyDef(Q, "Q", True)
G_KeyDef(R, "R", True)
G_KeyDef(S, "S", True)
G_KeyDef(T, "T", True)
G_KeyDef(U, "U", True)
G_KeyDef(V, "V", True)
G_KeyDef(W, "W", True)
G_KeyDef(X, "X", True)
G_KeyDef(Y, "Y", True)
G_KeyDef(Z, "Z", True)
G_KeyDef(Space, "Space", True)
G_KeyDef(Period, "Period", True)
G_KeyDef(ForwardSlash, "Forward slash", True)
G_KeyDef(Comma, "Comma", True)
G_KeyDef(Quote, "Quote", True)
G_KeyDef(Colon, "Colon", True)
G_KeyDef(LeftBracket, "Left bracket", True)
G_KeyDef(RightBracket, "Right bracket", True)
G_KeyDef(PRINTABLE_END, "ERROR - invalid key", False)

G_KeyDef(Tab, "Tab", True) // TODO(tbt): this is a hack to stop text edits consuming tab key presses
G_KeyDef(F1, "F1", True)
G_KeyDef(F2, "F2", True)
G_KeyDef(F3, "F3", True)
G_KeyDef(F4, "F4", True)
G_KeyDef(F5, "F5", True)
G_KeyDef(F6, "F6", True)
G_KeyDef(F7, "F7", True)
G_KeyDef(F8, "F8", True)
G_KeyDef(F9, "F9", True)
G_KeyDef(F10, "F10", True)
G_KeyDef(F11, "F11", True)
G_KeyDef(F12, "F12", True)
G_KeyDef(Backspace, "Backspace", True)
G_KeyDef(Delete, "Delete", True)
G_KeyDef(Insert, "Insert", True)
G_KeyDef(Esc, "Escape", True)
G_KeyDef(Enter, "Enter", True)
G_KeyDef(Up, "Up", True)
G_KeyDef(Left, "Left", True)
G_KeyDef(Down, "Down", True)
G_KeyDef(Right, "Right", True)
G_KeyDef(PageUp, "Page up", True)
G_KeyDef(PageDown, "Page down", True)
G_KeyDef(Home, "Home", True)
G_KeyDef(End, "End", True)

G_KeyDef(MODIFIER_BEGIN, "ERROR - invalid key", False)
G_KeyDef(Ctrl, "Ctrl", True)
G_KeyDef(Shift, "Shift", True)
G_KeyDef(Alt, "Alt", True)
G_KeyDef(Super, "Super", True)
G_KeyDef(MODIFIER_END, "ERROR - invalid key", False)

G_KeyDef(MOUSE_BEGIN, "ERROR - invalid key", False)
G_KeyDef(MouseButtonLeft, "Left mouse button", True)
G_KeyDef(MouseButtonMiddle, "Middle mouse button", True)
G_KeyDef(MouseButtonRight, "Right mouse button", True)
G_KeyDef(MouseButtonForward, "Forward mouse button", True)
G_KeyDef(MouseButtonBackward, "Backward mouse button", True)
G_KeyDef(MouseButtonDoubleClick, "Double click", True)
G_KeyDef(MOUSE_END, "ERROR - invalid key", False)

G_KeyDef(MAX, "ERROR - invalid key", False)

#undef G_KeyDef
